# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BpFusion < Formula
  desc "CLI for Bitpanda Fusion API"
  homepage "https://github.com/bitpanda-labs/bitpanda-fusion-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bitpanda-labs/bitpanda-fusion-cli/releases/download/v0.1.0/bitpanda-fusion-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "cb9c81e12cdde89eeccc75db9b733abcf1def75e82d8898956d5b612cb641896"

      define_method(:install) do
        bin.install "bp-fusion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bitpanda-labs/bitpanda-fusion-cli/releases/download/v0.1.0/bitpanda-fusion-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "1ff0c82576867041c68f4685041fb5682bc8b7eff6ea521845766adfaa10d054"

      define_method(:install) do
        bin.install "bp-fusion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitpanda-labs/bitpanda-fusion-cli/releases/download/v0.1.0/bitpanda-fusion-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "e2b7a103b7f288511063e122a9783a6598e7907e5bf46c4745fd9eb1fed95e32"
      define_method(:install) do
        bin.install "bp-fusion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitpanda-labs/bitpanda-fusion-cli/releases/download/v0.1.0/bitpanda-fusion-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "0143acc730e56d958cee4181e562eb5431a23d47b1aabec248cd9342a4dc5cb6"
      define_method(:install) do
        bin.install "bp-fusion"
      end
    end
  end

  test do
    system "#{bin}/bp-fusion", "--version"
  end
end
