# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BpFusion < Formula
  desc "CLI for Bitpanda Fusion API"
  homepage "https://github.com/bitpanda-labs/bitpanda-fusion-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bitpanda-labs/bitpanda-fusion-cli/releases/download/v0.1.0/bitpanda-fusion-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "801b7129dd82a4dd893d8006df1c7767a031af69fd265498049d7275b4a1a632"

      define_method(:install) do
        bin.install "bp-fusion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bitpanda-labs/bitpanda-fusion-cli/releases/download/v0.1.0/bitpanda-fusion-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "3590a911e0fb67fa0f9d1b63e186f5c65eb0f59b43dcc80cf3cc0b92b2b87834"

      define_method(:install) do
        bin.install "bp-fusion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitpanda-labs/bitpanda-fusion-cli/releases/download/v0.1.0/bitpanda-fusion-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "f27ec88c05845f68fe030072a83e8cefe99f17013b25484077238aea696caeea"
      define_method(:install) do
        bin.install "bp-fusion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitpanda-labs/bitpanda-fusion-cli/releases/download/v0.1.0/bitpanda-fusion-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "d9b706270268ce0a52055410ad56314fb643831aeca39cd4f656ab4ad846e628"
      define_method(:install) do
        bin.install "bp-fusion"
      end
    end
  end

  test do
    system "#{bin}/bp-fusion", "--version"
  end
end
