# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bp < Formula
  desc "CLI for Bitpanda Developer API"
  homepage "https://github.com/bitpanda-labs/bitpanda-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bitpanda-labs/bitpanda-cli/releases/download/v0.1.0/bitpanda-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "984d30d77b21066efc379c5305cdfd16a37076bdf7d08d4104256f5e35344230"

      define_method(:install) do
        bin.install "bp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bitpanda-labs/bitpanda-cli/releases/download/v0.1.0/bitpanda-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "dd3d80ff70fc877c1bbbaec04ae73b22cc394f95f6385f4765395b617b6f0e00"

      define_method(:install) do
        bin.install "bp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitpanda-labs/bitpanda-cli/releases/download/v0.1.0/bitpanda-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "591120b2f775681bc614c58917d8af4fe9bdebd1abc1c7c3207cddc64d4c70a2"
      define_method(:install) do
        bin.install "bp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitpanda-labs/bitpanda-cli/releases/download/v0.1.0/bitpanda-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "7297702b824e715a483a77efc896384d262357392030fc0e3cc8e1d7faa8fa0c"
      define_method(:install) do
        bin.install "bp"
      end
    end
  end

  test do
    system "#{bin}/bp", "--version"
  end
end
