# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bp < Formula
  desc "CLI for Bitpanda Developer API"
  homepage "https://github.com/bitpanda-labs/bitpanda-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bitpanda-labs/bitpanda-cli/releases/download/v0.2.0/bitpanda-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "5e2ebaada5511a51bf6e7aa4abb1d83a78be72d9534a879ae1ecd28617212c38"

      define_method(:install) do
        bin.install "bp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bitpanda-labs/bitpanda-cli/releases/download/v0.2.0/bitpanda-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "05ffdb2c5c11ac9db61dece49f73ca747d62182648d48840a4a18cc6bdd8a27c"

      define_method(:install) do
        bin.install "bp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitpanda-labs/bitpanda-cli/releases/download/v0.2.0/bitpanda-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "2211dacee383b941092f033b599f99c3976375372d7400ad21f319b56a849dd4"
      define_method(:install) do
        bin.install "bp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bitpanda-labs/bitpanda-cli/releases/download/v0.2.0/bitpanda-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "386ab7c8b47954371e487a2d2d99a1bc5f47f2991a0701da68bc681da7ebce4c"
      define_method(:install) do
        bin.install "bp"
      end
    end
  end

  test do
    system "#{bin}/bp", "--version"
  end
end
